---
- name: Converge
  hosts: all
  roles:
    - role: wpcli-wrapper
  tasks:
    - name: ensure path exists for WordPress
      file:
        path: "{{ wordpress_path }}"
        state: directory
        mode: 0775
        owner: root
        group: root
    - name: download wordpress
      wpcli_core:
        path: "{{ wordpress_path }}"
        action: download
        version: "{{ wordpress_version }}"
    - name: create wp-config.php
      wpcli_config:
        path: "{{ wordpress_path }}"
        action: create
        dbname: "{{ wordpress_dbname }}"
        dbuser: "{{ wordpress_dbuser }}"
        dbpass: "{{ wordpress_dbpass }}"
