---
- name: Prepare
  hosts: all
  roles:
    - role: geerlingguy.repo-epel
    - role: geerlingguy.repo-remi
  gather_facts: true
  tasks:
    - name: install php-cli
      yum:
        name: php-cli
        state: installed
        enablerepo: remi-php72
    - name: install needed packages
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - mysql
        - mariadb-server
        - MySQL-python
    - name: start mysql
      service:
        name: mariadb
        state: started
    - name: create mysql database
      mysql_db:
        name: "{{ wordpress_dbname }}"
        state: present
    - name: create mysql user
      mysql_user:
        name: "{{ wordpress_dbuser }}"
        state: present
        password: "{{ wordpress_dbpass }}"
        priv: 'wp.*:ALL'
